name: publish

on:
  push:
    branches: [main, dev]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GHCR Login
      uses: khlam/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and publish
      run: |
        docker build . --squash --tag ghcr.io/${{ github.repository }}/latexmk:latest
        docker run ghcr.io/${{ github.repository }}/latexmk:latest
        docker push ghcr.io/${{ github.repository }}/latexmk:latest

jobs:
  config-generator:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Create a text file with random numbers
        run: echo $((1 + $RANDOM % 99999999)) > README.md

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config --global user.name ${GH_USERNAME}
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git add -A
          git commit -m '[automated commit] created value'
          git push